apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test01
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: web-deploy
  template:
    metadata:
      labals:
        app.kubernetes.io/name: web-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
